---
machines:
  - name: mail
    box: obsd72
    vars:
      net:
        ifaces:
          - name: vio0
          - name: vio1
            addr: 172.16.123.74
            netmask: 255.255.255.0
      mail:
        listen:
          - addr: all
            port: smtp
            tls: true
            filter: spam
          - addr: all
            port: submission
            tls: force
            auth: true
            dkim: true
            filter: no
        domains:
          - fsaisgud.com
